name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: npm install, deploy
        run: |
          npm install
          npm run deploy
      
      - name: Deploy to ECS
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: xupeng.name
          key: ${{ secrets.SITE_KEY }}
          script: |
            cd /var/www/xupeng.name
            git --version
