name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Deploy Site Content
        run: |
          mkdir ~/.ssh/
          echo '${{ secrets.GH_KEY }}' > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519

          npm install
          npm run deploy

          rm ~/.ssh/id_ed25519
      
      - name: Update Site Content
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: xupeng.name
          username: ${{ secrets.SITE_USERNAME }}
          key: ${{ secrets.SITE_KEY }}
          script: |
            systemctl stop nginx
            cd /var/www
            rm -rf xupeng.name

            git init xupeng.name
            cd xupeng.name
            git remote add origin git@github.com:athrunsaga/xupeng.name.git
            git fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin pages
            git checkout --force -B pages refs/remotes/origin/pages

            systemctl start nginx
